CREATE TABLE operaciones_sucursal (
    id SERIAL PRIMARY KEY,
    usuario_apertura_id INT,
    usuario_cierre_id INT,
    sucursal_id INT NOT NULL,
    estatus_id INT,
    fecha_inicio TIMESTAMP NOT NULL,
    fecha_fin TIMESTAMP,
    valor_inicial_inventario DECIMAL(18,6) DEFAULT 0,
    valor_compras DECIMAL(18,6) DEFAULT 0,
    valor_ventas DECIMAL(18,6) DEFAULT 0,
    descuentos_aplicados DECIMAL(18,6) DEFAULT 0,
    ajuste_inventario DECIMAL(18,6) DEFAULT 0,
    valor_final_inventario DECIMAL(18,6) DEFAULT 0,
    ingreso_efectivo DECIMAL(18,6) DEFAULT 0,
    ingreso_tarjetas DECIMAL(18,6) DEFAULT 0,
    ingreso_cheques DECIMAL(18,6) DEFAULT 0,
    ingreso_transferencia DECIMAL(18,6) DEFAULT 0,
    ingreso_otros DECIMAL(18,6) DEFAULT 0,
    creditos DECIMAL(18,6) DEFAULT 0,
    vales_salida DECIMAL(18,6) DEFAULT 0,
    vales_entrantes DECIMAL(18,6) DEFAULT 0,
    cfdi_efectivo DECIMAL(18,6) DEFAULT 0,
    cfdi_tarjetas DECIMAL(18,6) DEFAULT 0,
    cfdi_cheques DECIMAL(18,6) DEFAULT 0,
    cfdi_transferencia DECIMAL(18,6) DEFAULT 0,
    cfdi_otros DECIMAL(18,6) DEFAULT 0,
    bajas_mercancia DECIMAL(18,6) DEFAULT 0,
    guid UUID DEFAULT gen_random_uuid() NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP,
    CONSTRAINT fk_operaciones_sucursal_apertura FOREIGN KEY (usuario_apertura_id) REFERENCES usuarios(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_operaciones_sucursal_cierre FOREIGN KEY (usuario_cierre_id) REFERENCES usuarios(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_operaciones_sucursal_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_operaciones_sucursal_estatus FOREIGN KEY (estatus_id) REFERENCES estatus(id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE UNIQUE INDEX idx_operaciones_sucursal_guid ON operaciones_sucursal(guid);
CREATE INDEX idx_operaciones_sucursal_deleted_at ON operaciones_sucursal(deleted_at);
CREATE INDEX idx_operaciones_sucursal_fecha_inicio ON operaciones_sucursal(fecha_inicio);
