// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ServiceActivateLicense(arg1) {
  return window['go']['main']['App']['ServiceActivateLicense'](arg1);
}

export function ServiceConfirmarTransaccion(arg1, arg2, arg3) {
  return window['go']['main']['App']['ServiceConfirmarTransaccion'](arg1, arg2, arg3);
}

export function ServiceConsultaProductos(arg1) {
  return window['go']['main']['App']['ServiceConsultaProductos'](arg1);
}

export function ServiceConsultarExistenciaProductos(arg1) {
  return window['go']['main']['App']['ServiceConsultarExistenciaProductos'](arg1);
}

export function ServiceGetEmpaques() {
  return window['go']['main']['App']['ServiceGetEmpaques']();
}

export function ServiceGetLineas() {
  return window['go']['main']['App']['ServiceGetLineas']();
}

export function ServiceGetMachineID() {
  return window['go']['main']['App']['ServiceGetMachineID']();
}

export function ServiceGetMarcas() {
  return window['go']['main']['App']['ServiceGetMarcas']();
}

export function ServiceGetSatFormasPago() {
  return window['go']['main']['App']['ServiceGetSatFormasPago']();
}

export function ServiceGetSatMetodosPago() {
  return window['go']['main']['App']['ServiceGetSatMetodosPago']();
}

export function ServiceGetSatProductos() {
  return window['go']['main']['App']['ServiceGetSatProductos']();
}

export function ServiceGetSatRegimenFiscal() {
  return window['go']['main']['App']['ServiceGetSatRegimenFiscal']();
}

export function ServiceGetSatUsosCFDI() {
  return window['go']['main']['App']['ServiceGetSatUsosCFDI']();
}

export function ServiceGetSucursales() {
  return window['go']['main']['App']['ServiceGetSucursales']();
}

export function ServiceLogin(arg1, arg2) {
  return window['go']['main']['App']['ServiceLogin'](arg1, arg2);
}

export function ServiceObtenerOperacionSucursal(arg1) {
  return window['go']['main']['App']['ServiceObtenerOperacionSucursal'](arg1);
}

export function ServiceObtenerTiposPedido() {
  return window['go']['main']['App']['ServiceObtenerTiposPedido']();
}

export function ServiceObtenerValorInventario() {
  return window['go']['main']['App']['ServiceObtenerValorInventario']();
}

export function ServiceResetPassword(arg1, arg2) {
  return window['go']['main']['App']['ServiceResetPassword'](arg1, arg2);
}

export function ServiceSucursalInicioOperacion(arg1) {
  return window['go']['main']['App']['ServiceSucursalInicioOperacion'](arg1);
}

export function ServiceVerifyLicense() {
  return window['go']['main']['App']['ServiceVerifyLicense']();
}

export function SyncEmpaques() {
  return window['go']['main']['App']['SyncEmpaques']();
}

export function SyncEmpresas() {
  return window['go']['main']['App']['SyncEmpresas']();
}

export function SyncLineas() {
  return window['go']['main']['App']['SyncLineas']();
}

export function SyncMarcas() {
  return window['go']['main']['App']['SyncMarcas']();
}

export function SyncNivelesEmpaque() {
  return window['go']['main']['App']['SyncNivelesEmpaque']();
}

export function SyncProductos() {
  return window['go']['main']['App']['SyncProductos']();
}

export function SyncSatFormasPago() {
  return window['go']['main']['App']['SyncSatFormasPago']();
}

export function SyncSatMetodosPago() {
  return window['go']['main']['App']['SyncSatMetodosPago']();
}

export function SyncSatProductos() {
  return window['go']['main']['App']['SyncSatProductos']();
}

export function SyncSatRegimenFiscal() {
  return window['go']['main']['App']['SyncSatRegimenFiscal']();
}

export function SyncSatUsosCfdi() {
  return window['go']['main']['App']['SyncSatUsosCfdi']();
}

export function SyncSucursalProductos(arg1) {
  return window['go']['main']['App']['SyncSucursalProductos'](arg1);
}

export function SyncSucursales() {
  return window['go']['main']['App']['SyncSucursales']();
}
