// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {requestdto} from '../models';
import {uuid} from '../models';
import {services} from '../models';
import {models} from '../models';

export function ServiceAbrirCaja(arg1:dto.AbrirCajaDto):Promise<dto.ResponseDto>;

export function ServiceActivateLicense(arg1:requestdto.ActivateLicenseRequest):Promise<any>;

export function ServiceApiCrearProducto(arg1:requestdto.ProductoCreate):Promise<dto.ResponseDto>;

export function ServiceBuscarClientes(arg1:string):Promise<Array<dto.ClienteDto>>;

export function ServiceCerrarCaja(arg1:dto.CerrarCajaDto):Promise<dto.ResponseDto>;

export function ServiceCerrarOperacionSucursal(arg1:dto.CerrarOperacionSucursalDto):Promise<dto.ResponseDto>;

export function ServiceConfirmarTransaccion(arg1:any,arg2:Array<dto.PagosAplicadosDto>,arg3:Array<dto.PedidoProductoDto>,arg4:any,arg5:any,arg6:any):Promise<dto.ResponseDto>;

export function ServiceConsultaProductos(arg1:string,arg2:boolean):Promise<Array<dto.ProductoDto>>;

export function ServiceConsultaTransacciones(arg1:any,arg2:any):Promise<dto.ResponseDto>;

export function ServiceConsultarExistenciaProductos(arg1:Array<uuid.UUID>):Promise<Array<dto.InventarioDto>>;

export function ServiceCotizacionConvertirAVenta(arg1:number,arg2:Array<dto.PagosAplicadosDto>,arg3:any):Promise<dto.ResponseDto>;

export function ServiceCotizacionObtenerDetalle(arg1:number):Promise<dto.CotizacionDetalleDto>;

export function ServiceCotizacionSolicitarAutorizacion(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<dto.ItemDescuentoDto>):Promise<dto.ResponseDto>;

export function ServiceGetEmpaques():Promise<dto.ResponseDto>;

export function ServiceGetKommerzConfig():Promise<services.KommerzConfig>;

export function ServiceGetLineas():Promise<dto.ResponseDto>;

export function ServiceGetLocalIP():Promise<string>;

export function ServiceGetMachineID():Promise<string>;

export function ServiceGetMarcas():Promise<dto.ResponseDto>;

export function ServiceGetSatFormasPago():Promise<dto.ResponseDto>;

export function ServiceGetSatMetodosPago():Promise<dto.ResponseDto>;

export function ServiceGetSatProductos():Promise<dto.ResponseDto>;

export function ServiceGetSatRegimenFiscal():Promise<dto.ResponseDto>;

export function ServiceGetSatUsosCFDI():Promise<dto.ResponseDto>;

export function ServiceGetSucursalGuid():Promise<string>;

export function ServiceGetSucursales():Promise<dto.ResponseDto>;

export function ServiceGetTiposAutorizacion():Promise<Array<dto.TipoAutorizacionDto>>;

export function ServiceGuardarInventarioJSON(arg1:string,arg2:string):Promise<dto.ResponseDto>;

export function ServiceIniciarAuditoria(arg1:string,arg2:string):Promise<dto.ResponseDto>;

export function ServiceLoadCloudCredentials():Promise<services.CloudCredentials>;

export function ServiceLogin(arg1:string,arg2:string):Promise<models.Usuario>;

export function ServiceObtenerOperacionCajeroActiva(arg1:number):Promise<dto.ResponseDto>;

export function ServiceObtenerOperacionSucursal(arg1:string):Promise<dto.ResponseDto>;

export function ServiceObtenerOperacionSucursalActiva(arg1:number):Promise<dto.ResponseDto>;

export function ServiceObtenerOperacionesCajero(arg1:number):Promise<dto.ResponseDto>;

export function ServiceObtenerResumenCajero(arg1:number):Promise<dto.ResponseDto>;

export function ServiceObtenerResumenInventario():Promise<dto.ResponseDto>;

export function ServiceObtenerSucursalLocal():Promise<dto.ResponseDto>;

export function ServiceObtenerTiposPedido():Promise<Array<models.TipoPedido>>;

export function ServiceObtenerValorInventario():Promise<dto.ResponseDto>;

export function ServiceResetPassword(arg1:string,arg2:string):Promise<models.Usuario>;

export function ServiceRestartApp():Promise<void>;

export function ServiceSaveCloudCredentials(arg1:string,arg2:string):Promise<void>;

export function ServiceSaveDBConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function ServiceSaveKommerzConfig(arg1:services.KommerzConfig):Promise<void>;

export function ServiceSucursalInicioOperacion(arg1:dto.SucursalInicioOperacionesDto):Promise<dto.ResponseDto>;

export function ServiceTestDBConnection(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<dto.ResponseDto>;

export function ServiceTestLocalServerConnection(arg1:string):Promise<dto.ResponseDto>;

export function ServiceVerificarAuditoriasEnCurso():Promise<dto.ResponseDto>;

export function ServiceVerifyLicense():Promise<dto.ResponseDto>;

export function SyncEmpaques():Promise<string>;

export function SyncEmpresas():Promise<string>;

export function SyncEstatus():Promise<string>;

export function SyncLineas():Promise<string>;

export function SyncMarcas():Promise<string>;

export function SyncNivelesEmpaque():Promise<string>;

export function SyncPerfiles():Promise<string>;

export function SyncProductos():Promise<string>;

export function SyncSatFormasPago():Promise<string>;

export function SyncSatMetodosPago():Promise<string>;

export function SyncSatProductos():Promise<string>;

export function SyncSatRegimenFiscal():Promise<string>;

export function SyncSatUsosCfdi():Promise<string>;

export function SyncSucursalProductos(arg1:Record<string, any>):Promise<string>;

export function SyncSucursales():Promise<string>;

export function SyncTiposAutorizacion():Promise<string>;

export function SyncTiposPedido():Promise<string>;

export function SyncUsuarios():Promise<string>;
