// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ServiceConsultaProductos(arg1) {
  return window['go']['main']['App']['ServiceConsultaProductos'](arg1);
}

export function SyncEmpaques() {
  return window['go']['main']['App']['SyncEmpaques']();
}

export function SyncEmpresas() {
  return window['go']['main']['App']['SyncEmpresas']();
}

export function SyncLineas() {
  return window['go']['main']['App']['SyncLineas']();
}

export function SyncMarcas() {
  return window['go']['main']['App']['SyncMarcas']();
}

export function SyncNivelesEmpaque() {
  return window['go']['main']['App']['SyncNivelesEmpaque']();
}

export function SyncProductos() {
  return window['go']['main']['App']['SyncProductos']();
}

export function SyncSatFormasPago() {
  return window['go']['main']['App']['SyncSatFormasPago']();
}

export function SyncSatMetodosPago() {
  return window['go']['main']['App']['SyncSatMetodosPago']();
}

export function SyncSatProductos() {
  return window['go']['main']['App']['SyncSatProductos']();
}

export function SyncSatRegimenFiscal() {
  return window['go']['main']['App']['SyncSatRegimenFiscal']();
}

export function SyncSatUsosCfdi() {
  return window['go']['main']['App']['SyncSatUsosCfdi']();
}

export function SyncSucursalProductos(arg1) {
  return window['go']['main']['App']['SyncSucursalProductos'](arg1);
}

export function SyncSucursales() {
  return window['go']['main']['App']['SyncSucursales']();
}
