// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {requestdto} from '../models';
import {dto} from '../models';
import {uuid} from '../models';
import {models} from '../models';

export function ServiceActivateLicense(arg1:requestdto.ActivateLicenseRequest):Promise<any>;

export function ServiceApiCrearProducto(arg1:requestdto.ProductoCreate):Promise<dto.ResponseDto>;

export function ServiceConfirmarTransaccion(arg1:any,arg2:Array<dto.PagosAplicadosDto>,arg3:Array<dto.PedidoProductoDto>,arg4:any,arg5:any):Promise<dto.ResponseDto>;

export function ServiceConsultaProductos(arg1:string):Promise<Array<dto.ProductoDto>>;

export function ServiceConsultaTransacciones():Promise<dto.ResponseDto>;

export function ServiceConsultarExistenciaProductos(arg1:Array<uuid.UUID>):Promise<Array<dto.InventarioDto>>;

export function ServiceGetEmpaques():Promise<dto.ResponseDto>;

export function ServiceGetLineas():Promise<dto.ResponseDto>;

export function ServiceGetMachineID():Promise<string>;

export function ServiceGetMarcas():Promise<dto.ResponseDto>;

export function ServiceGetSatFormasPago():Promise<dto.ResponseDto>;

export function ServiceGetSatMetodosPago():Promise<dto.ResponseDto>;

export function ServiceGetSatProductos():Promise<dto.ResponseDto>;

export function ServiceGetSatRegimenFiscal():Promise<dto.ResponseDto>;

export function ServiceGetSatUsosCFDI():Promise<dto.ResponseDto>;

export function ServiceGetSucursales():Promise<dto.ResponseDto>;

export function ServiceLogin(arg1:string,arg2:string):Promise<models.Usuario>;

export function ServiceObtenerOperacionSucursal(arg1:string):Promise<dto.ResponseDto>;

export function ServiceObtenerTiposPedido():Promise<Array<models.TipoPedido>>;

export function ServiceObtenerValorInventario():Promise<dto.ResponseDto>;

export function ServiceResetPassword(arg1:string,arg2:string):Promise<models.Usuario>;

export function ServiceSucursalInicioOperacion(arg1:dto.SucursalInicioOperacionesDto):Promise<dto.ResponseDto>;

export function ServiceVerifyLicense():Promise<dto.ResponseDto>;

export function SyncEmpaques():Promise<string>;

export function SyncEmpresas():Promise<string>;

export function SyncLineas():Promise<string>;

export function SyncMarcas():Promise<string>;

export function SyncNivelesEmpaque():Promise<string>;

export function SyncProductos():Promise<string>;

export function SyncSatFormasPago():Promise<string>;

export function SyncSatMetodosPago():Promise<string>;

export function SyncSatProductos():Promise<string>;

export function SyncSatRegimenFiscal():Promise<string>;

export function SyncSatUsosCfdi():Promise<string>;

export function SyncSucursalProductos(arg1:Record<string, any>):Promise<string>;

export function SyncSucursales():Promise<string>;
