// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NetPayAuthGetToken() {
  return window['go']['main']['App']['NetPayAuthGetToken']();
}

export function NetPaySaleTransaction(arg1) {
  return window['go']['main']['App']['NetPaySaleTransaction'](arg1);
}

export function ServiceAbrirCaja(arg1) {
  return window['go']['main']['App']['ServiceAbrirCaja'](arg1);
}

export function ServiceActivateLicense(arg1) {
  return window['go']['main']['App']['ServiceActivateLicense'](arg1);
}

export function ServiceApiCrearProducto(arg1) {
  return window['go']['main']['App']['ServiceApiCrearProducto'](arg1);
}

export function ServiceBuscarClientes(arg1) {
  return window['go']['main']['App']['ServiceBuscarClientes'](arg1);
}

export function ServiceBuscarEntidadFiscalPorRFC(arg1) {
  return window['go']['main']['App']['ServiceBuscarEntidadFiscalPorRFC'](arg1);
}

export function ServiceBuscarEntidadFiscalProveedor(arg1) {
  return window['go']['main']['App']['ServiceBuscarEntidadFiscalProveedor'](arg1);
}

export function ServiceBuscarEntidadesFacturacion(arg1) {
  return window['go']['main']['App']['ServiceBuscarEntidadesFacturacion'](arg1);
}

export function ServiceBuscarProveedores(arg1) {
  return window['go']['main']['App']['ServiceBuscarProveedores'](arg1);
}

export function ServiceCancelarVenta(arg1) {
  return window['go']['main']['App']['ServiceCancelarVenta'](arg1);
}

export function ServiceCerrarCaja(arg1) {
  return window['go']['main']['App']['ServiceCerrarCaja'](arg1);
}

export function ServiceCerrarOperacionSucursal(arg1) {
  return window['go']['main']['App']['ServiceCerrarOperacionSucursal'](arg1);
}

export function ServiceConfirmarTransaccion(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ServiceConfirmarTransaccion'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ServiceConsultaProductos(arg1, arg2) {
  return window['go']['main']['App']['ServiceConsultaProductos'](arg1, arg2);
}

export function ServiceConsultaTransacciones(arg1, arg2) {
  return window['go']['main']['App']['ServiceConsultaTransacciones'](arg1, arg2);
}

export function ServiceConsultarExistenciaProductos(arg1) {
  return window['go']['main']['App']['ServiceConsultarExistenciaProductos'](arg1);
}

export function ServiceConsultarHistorialCompras() {
  return window['go']['main']['App']['ServiceConsultarHistorialCompras']();
}

export function ServiceConsultarTransferencias() {
  return window['go']['main']['App']['ServiceConsultarTransferencias']();
}

export function ServiceCotizacionConvertirAVenta(arg1, arg2, arg3) {
  return window['go']['main']['App']['ServiceCotizacionConvertirAVenta'](arg1, arg2, arg3);
}

export function ServiceCotizacionObtenerDetalle(arg1) {
  return window['go']['main']['App']['ServiceCotizacionObtenerDetalle'](arg1);
}

export function ServiceCotizacionSolicitarAutorizacion(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ServiceCotizacionSolicitarAutorizacion'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ServiceCrearCompra(arg1) {
  return window['go']['main']['App']['ServiceCrearCompra'](arg1);
}

export function ServiceCrearSolicitudProductos(arg1) {
  return window['go']['main']['App']['ServiceCrearSolicitudProductos'](arg1);
}

export function ServiceDeleteReceiptLogo() {
  return window['go']['main']['App']['ServiceDeleteReceiptLogo']();
}

export function ServiceEmailReceipt(arg1, arg2) {
  return window['go']['main']['App']['ServiceEmailReceipt'](arg1, arg2);
}

export function ServiceEmitirFacturacion(arg1) {
  return window['go']['main']['App']['ServiceEmitirFacturacion'](arg1);
}

export function ServiceEnviarFacturaCorreo(arg1) {
  return window['go']['main']['App']['ServiceEnviarFacturaCorreo'](arg1);
}

export function ServiceGeneratePurchaseReport(arg1) {
  return window['go']['main']['App']['ServiceGeneratePurchaseReport'](arg1);
}

export function ServiceGenerateSaleDocument(arg1) {
  return window['go']['main']['App']['ServiceGenerateSaleDocument'](arg1);
}

export function ServiceGetEmpaques() {
  return window['go']['main']['App']['ServiceGetEmpaques']();
}

export function ServiceGetKommerzConfig() {
  return window['go']['main']['App']['ServiceGetKommerzConfig']();
}

export function ServiceGetLineas() {
  return window['go']['main']['App']['ServiceGetLineas']();
}

export function ServiceGetLocalIP() {
  return window['go']['main']['App']['ServiceGetLocalIP']();
}

export function ServiceGetMachineID() {
  return window['go']['main']['App']['ServiceGetMachineID']();
}

export function ServiceGetMarcas() {
  return window['go']['main']['App']['ServiceGetMarcas']();
}

export function ServiceGetSatFormasPago() {
  return window['go']['main']['App']['ServiceGetSatFormasPago']();
}

export function ServiceGetSatMetodosPago() {
  return window['go']['main']['App']['ServiceGetSatMetodosPago']();
}

export function ServiceGetSatProductos() {
  return window['go']['main']['App']['ServiceGetSatProductos']();
}

export function ServiceGetSatRegimenFiscal() {
  return window['go']['main']['App']['ServiceGetSatRegimenFiscal']();
}

export function ServiceGetSatUsosCFDI() {
  return window['go']['main']['App']['ServiceGetSatUsosCFDI']();
}

export function ServiceGetSucursalGuid() {
  return window['go']['main']['App']['ServiceGetSucursalGuid']();
}

export function ServiceGetSucursales() {
  return window['go']['main']['App']['ServiceGetSucursales']();
}

export function ServiceGetTiposAutorizacion() {
  return window['go']['main']['App']['ServiceGetTiposAutorizacion']();
}

export function ServiceGuardarCliente(arg1) {
  return window['go']['main']['App']['ServiceGuardarCliente'](arg1);
}

export function ServiceGuardarInventarioJSON(arg1, arg2) {
  return window['go']['main']['App']['ServiceGuardarInventarioJSON'](arg1, arg2);
}

export function ServiceGuardarProveedor(arg1) {
  return window['go']['main']['App']['ServiceGuardarProveedor'](arg1);
}

export function ServiceIniciarAuditoria(arg1, arg2) {
  return window['go']['main']['App']['ServiceIniciarAuditoria'](arg1, arg2);
}

export function ServiceListarClientes() {
  return window['go']['main']['App']['ServiceListarClientes']();
}

export function ServiceLoadCloudCredentials() {
  return window['go']['main']['App']['ServiceLoadCloudCredentials']();
}

export function ServiceLoadReceiptLogo() {
  return window['go']['main']['App']['ServiceLoadReceiptLogo']();
}

export function ServiceLogin(arg1, arg2) {
  return window['go']['main']['App']['ServiceLogin'](arg1, arg2);
}

export function ServiceObtenerCliente(arg1) {
  return window['go']['main']['App']['ServiceObtenerCliente'](arg1);
}

export function ServiceObtenerFacturaPDF(arg1) {
  return window['go']['main']['App']['ServiceObtenerFacturaPDF'](arg1);
}

export function ServiceObtenerOperacionCajeroActiva(arg1) {
  return window['go']['main']['App']['ServiceObtenerOperacionCajeroActiva'](arg1);
}

export function ServiceObtenerOperacionSucursal(arg1) {
  return window['go']['main']['App']['ServiceObtenerOperacionSucursal'](arg1);
}

export function ServiceObtenerOperacionSucursalActiva(arg1) {
  return window['go']['main']['App']['ServiceObtenerOperacionSucursalActiva'](arg1);
}

export function ServiceObtenerOperacionesCajero(arg1) {
  return window['go']['main']['App']['ServiceObtenerOperacionesCajero'](arg1);
}

export function ServiceObtenerResumenCajero(arg1) {
  return window['go']['main']['App']['ServiceObtenerResumenCajero'](arg1);
}

export function ServiceObtenerResumenInventario() {
  return window['go']['main']['App']['ServiceObtenerResumenInventario']();
}

export function ServiceObtenerResumenVentasOperacion(arg1) {
  return window['go']['main']['App']['ServiceObtenerResumenVentasOperacion'](arg1);
}

export function ServiceObtenerSucursalLocal() {
  return window['go']['main']['App']['ServiceObtenerSucursalLocal']();
}

export function ServiceObtenerTiposPedido() {
  return window['go']['main']['App']['ServiceObtenerTiposPedido']();
}

export function ServiceObtenerValorInventario() {
  return window['go']['main']['App']['ServiceObtenerValorInventario']();
}

export function ServiceOpenInvoiceLocation(arg1) {
  return window['go']['main']['App']['ServiceOpenInvoiceLocation'](arg1);
}

export function ServicePrepararFacturacion(arg1) {
  return window['go']['main']['App']['ServicePrepararFacturacion'](arg1);
}

export function ServicePrintReceipt(arg1) {
  return window['go']['main']['App']['ServicePrintReceipt'](arg1);
}

export function ServiceResetPassword(arg1, arg2) {
  return window['go']['main']['App']['ServiceResetPassword'](arg1, arg2);
}

export function ServiceRestartApp() {
  return window['go']['main']['App']['ServiceRestartApp']();
}

export function ServiceSaveCloudCredentials(arg1, arg2) {
  return window['go']['main']['App']['ServiceSaveCloudCredentials'](arg1, arg2);
}

export function ServiceSaveDBConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ServiceSaveDBConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ServiceSaveKommerzConfig(arg1) {
  return window['go']['main']['App']['ServiceSaveKommerzConfig'](arg1);
}

export function ServiceSaveReceiptLogo(arg1) {
  return window['go']['main']['App']['ServiceSaveReceiptLogo'](arg1);
}

export function ServiceSelectInvoiceFolder() {
  return window['go']['main']['App']['ServiceSelectInvoiceFolder']();
}

export function ServiceSucursalInicioOperacion(arg1) {
  return window['go']['main']['App']['ServiceSucursalInicioOperacion'](arg1);
}

export function ServiceTestDBConnection(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ServiceTestDBConnection'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ServiceTestLocalServerConnection(arg1) {
  return window['go']['main']['App']['ServiceTestLocalServerConnection'](arg1);
}

export function ServiceTestPrintReceipt(arg1) {
  return window['go']['main']['App']['ServiceTestPrintReceipt'](arg1);
}

export function ServiceVerificarAuditoriasEnCurso() {
  return window['go']['main']['App']['ServiceVerificarAuditoriasEnCurso']();
}

export function ServiceVerifyLicense() {
  return window['go']['main']['App']['ServiceVerifyLicense']();
}

export function SyncClientes() {
  return window['go']['main']['App']['SyncClientes']();
}

export function SyncEmpaques() {
  return window['go']['main']['App']['SyncEmpaques']();
}

export function SyncEmpresas() {
  return window['go']['main']['App']['SyncEmpresas']();
}

export function SyncEstatus() {
  return window['go']['main']['App']['SyncEstatus']();
}

export function SyncLineas() {
  return window['go']['main']['App']['SyncLineas']();
}

export function SyncMarcas() {
  return window['go']['main']['App']['SyncMarcas']();
}

export function SyncNivelesEmpaque() {
  return window['go']['main']['App']['SyncNivelesEmpaque']();
}

export function SyncPerfiles() {
  return window['go']['main']['App']['SyncPerfiles']();
}

export function SyncProductos() {
  return window['go']['main']['App']['SyncProductos']();
}

export function SyncRolesFiscales() {
  return window['go']['main']['App']['SyncRolesFiscales']();
}

export function SyncSatFormasPago() {
  return window['go']['main']['App']['SyncSatFormasPago']();
}

export function SyncSatMetodosPago() {
  return window['go']['main']['App']['SyncSatMetodosPago']();
}

export function SyncSatProductos() {
  return window['go']['main']['App']['SyncSatProductos']();
}

export function SyncSatRegimenFiscal() {
  return window['go']['main']['App']['SyncSatRegimenFiscal']();
}

export function SyncSatUsosCfdi() {
  return window['go']['main']['App']['SyncSatUsosCfdi']();
}

export function SyncSucursalProductos(arg1) {
  return window['go']['main']['App']['SyncSucursalProductos'](arg1);
}

export function SyncSucursales() {
  return window['go']['main']['App']['SyncSucursales']();
}

export function SyncTiposAutorizacion() {
  return window['go']['main']['App']['SyncTiposAutorizacion']();
}

export function SyncTiposPedido() {
  return window['go']['main']['App']['SyncTiposPedido']();
}

export function SyncUsuarios() {
  return window['go']['main']['App']['SyncUsuarios']();
}
