// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function ServiceConsultaProductos(arg1:string):Promise<Array<dto.ProductoDto>>;

export function SyncEmpaques():Promise<string>;

export function SyncEmpresas():Promise<string>;

export function SyncLineas():Promise<string>;

export function SyncMarcas():Promise<string>;

export function SyncNivelesEmpaque():Promise<string>;

export function SyncProductos():Promise<string>;

export function SyncSatFormasPago():Promise<string>;

export function SyncSatMetodosPago():Promise<string>;

export function SyncSatProductos():Promise<string>;

export function SyncSatRegimenFiscal():Promise<string>;

export function SyncSatUsosCfdi():Promise<string>;

export function SyncSucursalProductos(arg1:Record<string, any>):Promise<string>;

export function SyncSucursales():Promise<string>;
